export const EXERCISE_CONFIG = {
  run: {
    distanceUnit: 'km',
    time: true,
    autoPace: true,
    paceLabel: 'min/km',
    weight: false,
    reps: false,
    repDistanceToggle: false,
  },
  skierg: {
    distanceUnit: 'm',
    time: true,
    autoPace: true,
    paceLabel: 'min/m',
    weight: false,
    reps: false,
    repDistanceToggle: false,
  },
  rowing: {
    distanceUnit: 'm',
    time: true,
    autoPace: true,
    paceLabel: 'min/m',
    weight: false,
    reps: false,
    repDistanceToggle: false,
  },
  sledpush: {
    distanceUnit: 'm',
    time: true,
    autoPace: false,
    weight: true,
    weightFormula: 'barbell',
    reps: false,
    repDistanceToggle: false,
  },
  sledpull: {
    distanceUnit: 'm',
    time: true,
    autoPace: false,
    weight: true,
    weightFormula: 'barbell',
    reps: false,
    repDistanceToggle: false,
  },
  burpee: {
    distanceUnit: 'm',
    time: false,
    autoPace: false,
    weight: false,
    reps: false,
    repDistanceToggle: true,
  },
  farmers: {
    distanceUnit: 'm',
    time: true,
    autoPace: false,
    weight: true,
    weightFormula: 'perHand',
    reps: false,
    repDistanceToggle: false,
  },
  sandbag: {
    distanceUnit: 'm',
    time: true,
    autoPace: false,
    weight: true,
    weightFormula: 'single',
    reps: false,
    repDistanceToggle: true,
  },
  wallball: {
    distanceUnit: null,
    time: true,
    autoPace: false,
    weight: true,
    weightFormula: 'single',
    reps: true,
    repDistanceToggle: false,
  },
};
